title: "Fitbot"
theme: minima

minima:
  social_link:
    github: "AY2122S1-CS2113T-F14-2/tp"
  
repository: "AY2122S1-CS2113T-F14-2/tp"

author:
  name:


header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

repository: "AY2122S1-CS2113T-F14-2/tp"

plugins:
  - jemoji


